"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let bike = "Ducati";
console.log("Bike is == 'Ducati'? I predict true");
console.log(bike == "Ducati");
console.log("Bike is == 'Civic'? I predict false");
console.log(bike == "Civic");
let car = "corolla";
console.log("car is == 'corolla'? I predict true");
console.log(car == "corolla");
console.log("car is == 'cultus'? I predict false");
console.log(car == "cultus");
